### ISSUE TITLE
Allow multiple rules on the same token pair

### ISSUE THREAD

**Issue by hensha256** [airswap/airswap-protocols#171]
### Description

In the current setup of the Delegate/Indexer/Index, a user cannot have multiple intents to trade on the same token pair. This is a situation that should be allowed on the contracts - take the following situation for example:
- At the rate of 200 DAI per WETH, Bob is willing to buy 5 WETH.
- At the rate of 80 DAI per WETH, Bob is willing to buy a lot more WETH - maybe 20

To set up such trades automatically on a Delegate contracts Bob would need multiple Rules on the same token pair, which isn't possible. Bob could instead deploy a second Delegate for his second rule (which is non-ideal but possible). However to actually stake his intent to trade on an Index (which is a token-pair-specific indexer), each user can only have one stake, due to the implementation using a mapping of user address.

This thereby makes the above situation impossible.

### Changes
- Allow multiple intents to trade to be set by one user on an Index. This would mean the mapping should be indexed by something different - for example hash(userAddress, nonce)
- Ideally also allow multiple rules to be set on the same Delegate for the same token pair. This could involve a mapping with nonces again, or better storing an array of Rules on each pairing.

**Comment by alicevhenshaw** [comment]
@poiresel and I spent a while discussing this and came to the following update:

- If a user wants to stake on a market, they shouldn't have to stake for each different rate at which they willing to trade. Furthermore, if a user updates a rule to trade a different amount or at a different rate you wouldnt expect them to re-stake.
- When the DelegateFrontend loops through different Delegates to find the best quote for a user, it calls, for example, `uint256 signerAmount = IDelegate(address(bytes20(locators[i]))).getSignerSideQuote(_senderAmount, _senderToken, _signerToken);`
- This means that it is down to the Delegate to return the price at which the Delegate is willing to trade the given tokens and amount.

For example, Bob has a Delegate with the following 2 rules:
- Delegate trades 5 WETH for DAI at 200 DAI per WETH
 Delegate trades 20 WETH for DAI at 250 DAI per WETH
(he gets more DAI for this second rule so is happy to trade more)

Alice wants to find a price for 10 WETH, where she buys them in DAI. Bob's Delegate would be called `getSignerSideQuote(10, WETH, DAI)`, and would return 2250 DAI as the signer's amount.
`2250 = 5*200 + 5*250`
This takes some WETH from each rule to get the best quote for the situation.

This means that all changes needed are needed for the Delegate:
- Store multiple rules per token pair market
- Have a more complex set of functions that calculate the best signer side and sender side quotes, that iterate and combine rules to give the best rate possible.
For ease of calculation, it would be sensible to store the rules in order of rate.

**Comment by alicevhenshaw** [comment]
A design to upgrade the delegate in the following ways:

- use (`signerAmount`, `senderAmount`) for rules instead of price/senderAmount

- use rule ids and follows standard `create` & `cancel` operations just like any other order book.

- allow multiple rules at different prices for a given pair (price is implied by signer/sender ratio)

To allow for the first and second points, our Rule struct will be updated to be as follows:

    struct Rule {
    	uint256 id;
    	uint256 signerAmount;
    	uint256 senderAmount;
    }

The main design change is around allowing one delegate to have multiple rules for the same token pair. Where the current contract has the following:

    // Mapping of senderToken to signerToken for rule lookup
    mapping (address => mapping (address => Rule)) public rules;

The new contract will instead have a linked list of Rules for each token pair. The list will maintain price order, with the price most beneficial for the `signer` at the beginning. I.e. the list will be in increasing value of `signerAmount / senderAmount`. Due to Solidity's truncation in division, we cannot simply perform this division, as if `signerToken` is less valuable than `senderToken`, and therefore `signerAmount` is larger than `senderAmount`, the division will always yield 0. Instead we use the following:

- Let's say that `price = makerAmount / takerAmount`
- We can abbreviate this to `p = m / t`
- So if we want to compare prices, we are trying to answer if `p1 > p2`
- This is then equivalent to asking if `m1 / t1 > m2 / t2`
- Then by multiplying by the denominators we get `m1 * t2 > m2 * t1`

**Comment by ejwessel** [comment]
I'll copy my comment from the doc:

> I'm assuming we're going to have another field in the delegate so that it's not just a doubly linked list but a hashed doubly linked list? 
mapping of id → rule
This make removal O(1)

Also, it looks like Rule not copied from our doc properly?
```
struct Rule {
    address senderToken;
    address signerToken;
    uint256 senderAmount;
    uint256 signerAmount;
    uint256 nextRuleID;
    uint256 prevRuleID;
  }
```

**Comment by alicevhenshaw** [comment]
What do you mean 'another field in the delegate'? What field are you thinking the contract needs? But yes, cancelling a rule is currently O(1).

Sorry about the struct being inconsistent - I updated it on notion but forgot to copy it across. The struct is now:
```
struct Rule {
    address senderToken;
    address signerToken;
    uint256 senderAmount;
    uint256 signerAmount;
    uint256 nextRuleID;
    uint256 prevRuleID;
  }
```
You need sender and signer token so that when you `cancelRule(ID)` you can look up whether that ID is the first rule in the `senderToken, signerToken` linked list and update it if needed.
