### ISSUE TITLE
Delegate msg.sender/tradeWallet stake amount

### ISSUE THREAD

**Issue by ejwessel** [airswap/airswap-protocols#234]
### Existing Functionality
Currently when `setRuleAndIntent()` is called staked tokens are provided by the msg.sender. Subsequently when `unsetRuleAndIntent()` is called, tokens are returned to the `msg.sender`.

### Proposed Functionality
`msg.sender` and `tradeWallet` should both be options on where staking tokens are pulled and returned from. A `defaultStakeAccount` can be set which can either be `msg.sender` or `tradeWallet`. Both `setRuleAndIntent()` and `unsetRuleAndIntent()` would first check against the defaultStakeAccount to know where to pull/return funds from/to.

**Comment by poiresel** [comment]
I disagree. tradeWallet has the role for being the wallet to fund and the money pot. Someone could make the tradeWallet and msg.sender be the same which would take this scenario into account. Allowing for switching between the two conflates the different roles participants play when using a delegate.

**Comment by alicevhenshaw** [comment]
I see Ethan's point. The reason we separated the tradeWallet was so that someone can have, for example, a cold wallet with their tokens in, and manage the delegate from a hot wallet instead. In this situation where the tokens are in their tradeWallet, it sounds like a fair assumption than their AST may be in their trade wallet too.
