### ISSUE TITLE
Delegate to Create Index during intent setting

### ISSUE THREAD

**Issue by ejwessel** [airswap/airswap-protocols#257]
### Context
>I think one thing we overlooked when reviewing the transactions is that in certain cases, delegates will need to create a new market in the indexer. If it does no exist.

>Yeah. I believe. What happens if a market was never created on the Indexer, and someone is setting a rule on a delegate?

### Existing Functionality
Say a user wants to `setRuleAndIntent()`, but the Index does not exist. 
A user would need to visit the index and explicitly open one.

### Proposed Functionality
setRuleAndIntent() would check if the Index exits and subsequently create it before setting an Intent.

### Reasoning
Reduce user friction.

**Comment by poiresel** [comment]
Feels that this was would be unexpected user behavior in that you'd end up spending 10x gas to create the Index.

**Comment by GalEldarDev** [comment]
From a UX perspective, I would argue that it would be best to batch the two transactions together. We will have to explain to the end-user the reason behind the increased gas fees or additional transactions in both cases. If we require users to submit an additional transaction to create a new index/market we will have to communicate why that is necessary. If we batch the two transactions, we will need to explain why the gas fees are higher than usual. I prefer that latter option since it requires one less step from the end-user, in an onboarding process that is already quite daunting. Simply put, we would have to explain to the user what is going on in both cases so we might as well also remove some possible friction.
