### ISSUE TITLE
Create a new pool function to accept individually signed claims

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#736]

**Comment by francisldn** [comment]
To do:
1. withdrawWithSignature should calculate amount from points rather than directly transfer the passed amount.
2. we should use nonce to mark claims as used. the Activate backend will issue claims with the same nonce until a Claim event is confirmed. then it'll issue claims with nonce + 1.
3. we can remove all other logic related to merkle trees and roots and limit to individually signed claims.
4. To use EIP712 for signing
